In [ ]:
'''
Использование библиотеки NumPy
Основным методом, используемым в numpy.linalg.solve
является метод LU-разложения (LU decomposition) и его вариации
'''
import numpy as np

# Коэффициенты системы уравнений
A = np.array([[ 168, -150, 11231284],
              [ 0,-185, 171],
              [-163123123, 190, -1]
             ], dtype=float)

b = np.array([-1711110, 777, -0], dtype=float)

# Решение системы
x = np.linalg.solve(A, b)

print("Решение системы с использованием numpy.linalg.solve:", x)

'''
Использование библиотеки SciPy
SciPy предлагает scipy.linalg.lu_solve
для решения системы с помощью LU-разложения
'''
from scipy.linalg import lu_factor, lu_solve

lu, piv = lu_factor(A)
x_lu = lu_solve((lu, piv), b)

print("Решение системы с использованием scipy.linalg:", x_lu)

Решение системы с использованием numpy.linalg.solve: [-5.05516376e-06 -4.34087636e+00 -1.52410101e-01]
Решение системы с использованием scipy.linalg: [-5.05516376e-06 -4.34087636e+00 -1.52410101e-01]


In [ ]:

A = np.array([[ 113.7777, -17.5555, 1199.999111],
              [ 0.797979,-33.3333, 17177777],
              [-133111, 0.19537, -133.13333]
             ], dtype=float)

b = np.array([-33333, 777, -31313], dtype=float)

def gauss(A, b):
    """
    Решение СЛАУ методом Гаусса.
    """
    numEquations = len(b)
    # Прямой ход
    for pivotRow in range(numEquations):
        for currentRow in range(pivotRow + 1, numEquations):
            factor = A[currentRow, pivotRow] / A[pivotRow, pivotRow]
            for currentCol in range(pivotRow, numEquations):
                A[currentRow, currentCol] -= factor * A[pivotRow, currentCol]
            b[currentRow] -= factor * b[pivotRow]

    # Обратный ход
    solutionVector = np.zeros(numEquations)
    for currentRow in range(numEquations - 1, -1, -1):
        sum_ax = 0
        for currentCol in range(currentRow + 1, numEquations):
            sum_ax += A[currentRow, currentCol] * solutionVector[currentCol]
        solutionVector[currentRow] = (b[currentRow] - sum_ax) / A[currentRow, currentRow]

    return solutionVector

print(gauss(A.copy(), b.copy()))

def gauss_elimination_with_partial_pivoting(matrix, vector):
    """
    Решает СЛАУ методом Гаусса с частичным выбором ведущего элемента.
    """
    matrix_size = len(matrix)

    # Прямой ход
    for current_column in range(matrix_size):
        max_index = np.argmax(np.abs(matrix[current_column:, current_column])) + current_column
        matrix[[current_column, max_index]] = matrix[[max_index, current_column]]
        vector[[current_column, max_index]] = vector[[max_index, current_column]]

        for i in range(current_column + 1, matrix_size):
            factor = matrix[i][current_column] / matrix[current_column][current_column]
            matrix[i, current_column:] -= factor * matrix[current_column, current_column:]
            vector[i] -= factor * vector[current_column]

    # Обратный ход
    solution = np.zeros(matrix_size)
    for i in range(matrix_size - 1, -1, -1):
        solution[i] = (vector[i] - np.dot(matrix[i, i + 1:], solution[i + 1:])) / matrix[i][i]

    return solution

print(gauss_elimination_with_partial_pivoting(A.copy(), b.copy()))

def lu_decomposition(matrix, vector):
    """
    Выполняет LU-разложение матрицы и решает СЛАУ с помощью этого разложения.
    """
    matrix_size = len(matrix)
    L = np.zeros((matrix_size, matrix_size))
    U = np.zeros((matrix_size, matrix_size))

    # LU разложение
    for row in range(matrix_size):
        L[row, row] = 1
        for col in range(row, matrix_size):
            sum_upper = sum(L[row, sum_index] * U[sum_index, col] for sum_index in range(row))
            U[row, col] = matrix[row, col] - sum_upper
        for col in range(row + 1, matrix_size):
            sum_lower = sum(L[col, sum_index] * U[sum_index, row] for sum_index in range(row))
            L[col, row] = (matrix[col, row] - sum_lower) / U[row, row]

    # Решение Ly = b для y
    y = np.zeros(matrix_size)
    for row in range(matrix_size):
        y[row] = vector[row] - np.dot(L[row, :row], y[:row])

    # Решение Ux = y для x
    x = np.zeros(matrix_size)
    for row in range(matrix_size - 1, -1, -1):
        x[row] = (y[row] - np.dot(U[row, row + 1:], x[row + 1:])) / U[row, row]

    return x

print(lu_decomposition(A.copy(), b.copy()))

[2.38025463e-01 1.90051903e+03 3.73315947e-03]
[2.38025463e-01 1.90051903e+03 3.73315947e-03]
[2.38025463e-01 1.90051903e+03 3.73315947e-03]
